name: Notificar actualizaci贸n

on:
  push:
    branches:
      - main

jobs:
  enviar_notificacion:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificaci贸n HTTP POST a ntfy.sh
        env:
          COMMIT_AUTHOR: ${{ github.actor }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          curl -X POST http://ntfy.sh/devops-itla \
            -d "Nueva actualizaci贸n de c贸digo por $COMMIT_AUTHOR. Ver commit: $COMMIT_URL"

